### ISSUE TITLE
compatibilty isdue 

### ISSUE THREAD

**Issue by ambz** [rookiepeng/Antenna-Design#1]
![Screenshot_20190602-181232](https://user-images.githubusercontent.com/43706529/58764738-e06c6480-8562-11e9-877d-982b1edba14c.png)
kindly any one  inform me how to resolve this issue 

how i can used cst files?

**Comment by ambz** [comment]
plz inform me

**Comment by rookiepeng** [comment]
It has been clearly stated in the error message, use a **commercial edition** of CST, not a **student version**

**Comment by ambz** [comment]
so how do i solve this isue bcz i dont hv comercial cst any soloution? Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Zhengyu Peng <notifications@github.com> Date: 23/06/2019  9:07 p.m.  (GMT+00:00) To: rookiepeng/antenna-models <antenna-models@noreply.github.com> Cc: ambz <ambreenjabbar7@gmail.com>, Author <author@noreply.github.com> Subject: Re: [rookiepeng/antenna-models] compatibilty isdue  (#1) Closed #1.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rookiepeng/antenna-models/issues/1?email_source=notifications\u0026email_token=AKNORIJH2QLFYD3VSYXUJODP37JZ7A5CNFSM4HSDDEV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSD7MUNQ#event-2432617014",
"url": "https://github.com/rookiepeng/antenna-models/issues/1?email_source=notifications\u0026email_token=AKNORIJH2QLFYD3VSYXUJODP37JZ7A5CNFSM4HSDDEV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSD7MUNQ#event-2432617014",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rookiepeng** [comment]
The only solution is purchasing a license from CST.
